import { Review } from "./types";

// Real-ish Seville spots, hand-placed coordinates around the centro.
export const mockReviews: Review[] = [
  {
    id: "1",
    place: "La Brunilda",
    category: "food",
    rating: 5,
    author: "marta_eats",
    comment: "Best tapas in El Arenal, the solomillo melts.",
    emoji: "🍳",
    lng: -5.9959,
    lat: 37.3866,
    createdAt: "2026-06-16T12:30:00Z",
  },
  {
    id: "2",
    place: "Bar El Comercio",
    category: "coffee",
    rating: 4,
    author: "seville_bites",
    comment: "Churros con chocolate, old-school vibe.",
    emoji: "☕",
    lng: -5.9893,
    lat: 37.3917,
    createdAt: "2026-06-16T09:05:00Z",
  },
  {
    id: "3",
    place: "Eslava",
    category: "food",
    rating: 5,
    author: "tapas_king",
    comment: "Slow-cooked egg over boletus cake. Iconic.",
    emoji: "🥚",
    lng: -5.9967,
    lat: 37.4011,
    createdAt: "2026-06-15T21:40:00Z",
  },
  {
    id: "4",
    place: "El Rinconcillo",
    category: "bar",
    rating: 4,
    author: "vino_lover",
    comment: "Oldest bar in Seville, tab chalked on the counter.",
    emoji: "🍷",
    lng: -5.9889,
    lat: 37.3955,
    createdAt: "2026-06-16T20:10:00Z",
  },
  {
    id: "5",
    place: "Heladería Rayas",
    category: "dessert",
    rating: 5,
    author: "sweet_tooth",
    comment: "Turrón ice cream, worth the queue.",
    emoji: "🍦",
    lng: -5.9925,
    lat: 37.3849,
    createdAt: "2026-06-16T18:20:00Z",
  },
  {
    id: "6",
    place: "Bar Alfalfa",
    category: "bar",
    rating: 4,
    author: "seville_bites",
    comment: "Tiny corner bar, killer salmorejo.",
    emoji: "🍅",
    lng: -5.9901,
    lat: 37.3902,
    createdAt: "2026-06-16T13:15:00Z",
  },
  {
    id: "7",
    place: "Confitería La Campana",
    category: "dessert",
    rating: 5,
    author: "sweet_tooth",
    comment: "Yema and tocino de cielo since 1885.",
    emoji: "🧁",
    lng: -5.9933,
    lat: 37.3923,
    createdAt: "2026-06-16T11:00:00Z",
  },
  {
    id: "8",
    place: "Ovejas Negras",
    category: "food",
    rating: 4,
    author: "tapas_king",
    comment: "Modern tapas near Santa Cruz, great wine list.",
    emoji: "🐑",
    lng: -5.9905,
    lat: 37.3878,
    createdAt: "2026-06-16T22:05:00Z",
  },
  {
    id: "9",
    place: "Café de Indias",
    category: "coffee",
    rating: 3,
    author: "coffee_run",
    comment: "Solid flat white, good for working.",
    emoji: "☕",
    lng: -5.9911,
    lat: 37.3889,
    createdAt: "2026-06-16T08:45:00Z",
  },
  {
    id: "10",
    place: "Mercado Lonja del Barranco",
    category: "food",
    rating: 4,
    author: "marta_eats",
    comment: "Food hall by the river, get the gambas.",
    emoji: "🦐",
    lng: -5.9978,
    lat: 37.3895,
    createdAt: "2026-06-16T14:30:00Z",
  },
];
